# W55FA93 series audio

#snd-soc-w55fa92-i2s-objs := w55fa92_i2s.o
#snd-soc-w55fa92-spu-objs := w55fa92_spu.o
#snd-soc-w55fa92-audio-objs := w55fa92_audio.o
#snd-soc-w55fa92-nau8822-objs := w55fa92_nau8822.o
#snd-soc-w55fa92-nau8810-objs := w55fa92_nau8810.o
#snd-soc-w55fa92-nau8814-objs := w55fa92_nau8814.o
# W55FA93 series audio

snd-soc-w55fa92-dac-objs := w55fa92_dac.o
snd-soc-w55fa92-spu-objs := w55fa92_spu.o
snd-soc-w55fa92-i2s-objs := w55fa92_i2s.o
snd-soc-w55fa92-pcm-objs := w55fa92_pcm.o
snd-soc-w55fa92-audio-objs := w55fa92_audio.o

obj-$(CONFIG_SND_SOC_W55FA92_SPU) += snd-soc-w55fa92-dac.o snd-soc-w55fa92-pcm.o snd-soc-w55fa92-spu.o snd-soc-w55fa92-audio.o 
obj-$(CONFIG_SND_SOC_W55FA92_I2S) += snd-soc-w55fa92-i2s.o snd-soc-w55fa92-pcm.o snd-soc-w55fa92-audio.o
