obj-$(CONFIG_INPUT_W55FA92_ADC)	+= w55fa92_platform_driver.o 
obj-$(CONFIG_TOUCH_DETECTION)		+= touch.o 
obj-$(CONFIG_BATTERY_DETECTION)		+= battery.o
obj-$(CONFIG_KEYPAD_DETECTION)		+= keypad.o
obj-$(CONFIG_INPUT_W55FA92_ADC)	+= w55fa92_hardware_adc.o 




