# W55FA92 series audio


snd-soc-w55fa92adc-adc-objs := w55fa92adc-adc.o
snd-soc-w55fa92adc-pcm-objs := w55fa92adc-pcm.o

obj-$(CONFIG_SND_SOC_W55FA92_ADC) += snd-soc-w55fa92adc-pcm.o
obj-$(CONFIG_SND_SOC_W55FA92_ADC) += snd-soc-w55fa92adc-adc.o

# Boards
snd-soc-w55fa92adc-audio-objs := w55fa92adc-audio.o
obj-$(CONFIG_SND_SOC_W55FA92_ADC) += snd-soc-w55fa92adc-audio.o
